Adding credibility signals feature
AFP-Medialab/verification-plugin pull request #562
Opened 2024-08-05 13:50 UTC by rosannamilner

This new feature adds six credibility signal classifiers:
- news framing (topic)
- news genre
- persuasion techniques
- subjectivity
- previous fact checks
- machine generated text

Related to https://github.com/AFP-Medialab/InVID-Translations/pull/93

2024-08-05 15:09 UTC, twinkarma requested changes
A few minor suggestion for changes but overall looking really good! Great work!

2024-08-05 15:09 UTC, twinkarma commented on src/components/NavItems/Assistant/AssistantScrapeResults/AssistantTextSpanClassification.jsx
> +  importantSentenceKey = "Important_Sentence",
This prop can be removed as it's not used in this class

2024-08-05 15:09 UTC, twinkarma commented on src/components/NavItems/Assistant/AssistantScrapeResults/AssistantTextClassification.jsx
> +export function ColourGradientTooltipContent({
Probably better to separate this and `ColourGradientScale` into its own file

2024-08-05 15:09 UTC, twinkarma commented on src/components/NavItems/Assistant/AssistantApiHandlers/useAssistantApi.jsx
> +    const result = await axios.post(assistantEndpoint + "dw/subjectivity", {
We'll want to add retries for this endpoint too. See function below.

2024-08-05 15:09 UTC, twinkarma commented on src/components/NavItems/Assistant/AssistantCheckResults/ExtractedSourceCredibilityDBKFDialog.jsx
> +                              {sourceCredibilityResults[key] ? (
Would this not always evaluate to true? The key value came from the `sourceCredibilityResults` after all.

2024-08-05 15:09 UTC, twinkarma commented on src/components/NavItems/Assistant/AssistantCheckResults/ExtractedSourceCredibilityDBKFDialog.jsx
> +                                ].credibilityScope.includes("/") ? (
Can just use `value` instead of `sourceCredibilityResults[key]`

2024-08-05 15:09 UTC, twinkarma commented on src/components/NavItems/Assistant/AssistantCheckResults/ExtractedSourceCredibilityDBKFDialog.jsx
> +                                ) : sourceCredibilityResults[key]
Same as above

2024-08-05 15:09 UTC, twinkarma commented on src/components/NavItems/Assistant/AssistantCheckResults/ExtractedSourceCredibilityDBKFDialog.jsx
> +                                      sourceCredibilityResults[key]
Same as above

2024-08-06 10:53 UTC, twinkarma approved these changes
LGTM!

2024-08-09 12:45 UTC, Sallaa requested changes
Just a check for Arabic (and LTR languages) but the rest looks good to me 👍

Please merge `beta-master` into your branch to also fix the conflicts

2024-08-09 12:45 UTC, Sallaa commented on src/components/NavItems/tools/SemanticSearch/components/ResultDisplayItem.jsx
> +                <Typography align="left">
Could you confirm this will work for arabic language? I think using `align="start"` would be better

2024-08-09 12:45 UTC, Sallaa commented on src/components/NavItems/tools/SemanticSearch/components/ResultDisplayItem.jsx
> +                <Typography align="left">
Same as above

2024-08-12 09:51 UTC, rosannamilner commented
> Just a check for Arabic (and LTR languages) but the rest looks good to me 👍
> 
> Please merge `beta-master` into your branch to also fix the conflicts

Thanks Valentin - noticing I don't have the languages drop down menu at the top, it appears empty and I'm struggling to work out why it's not appearing. (Checked for this branch and same on beta-master). Do you have any ideas why this could be happening?

![image (36)](https://github.com/user-attachments/assets/c65bb7b7-a28b-4227-a00c-0a2a35455206)

Looking into components/Navitems/languages/languages.jsx, storeLanguage prints out as "en" but languageList is empty.

2024-08-12 10:14 UTC, Sallaa commented
@rosannamilner this usually happens when you are pointing to the wrong branch or when you are offline (no internet connection)

Can you try the following troubleshooting?
1. Merge beta-master into your branch to get the latest code (this will also allow you to fix remaining conflicts)
2. Make sure your .env config uses `REACT_APP_TRANSLATION_TAG=v0.82`
3. If you changed your `.env` configuration, run `npm run dev` again
4. Uninstall / reinstall the plugin on Chrome or do a hard reload and clear the cache (open the Chrome inspector, then hold the refresh button in chrome to see the Empty Cache and Hard Reload option)
5. Double check your internet connection just in case

Let me know if you still face the issue after this

2024-08-12 10:16 UTC, Sallaa commented
Also, let me know if you see error messages in the console. They could indicate where the problem is coming from

2024-08-12 11:02 UTC, rosannamilner commented
> Also, let me know if you see error messages in the console. They could indicate where the problem is coming from

I have done the above with no luck, but I do see these errors in the console:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND    undefined/dictionaries/components/NavItems/defaultLanguage.tsv?lang=en&tag=v0.82:1
Failed to load resource: net::ERR_FILE_NOT_FOUND    undefined/languages?tag=v0.82:1    
```

2024-08-26 08:44 UTC, Sallaa approved these changes

2024-08-26 08:44 UTC, merged