Display scraped youtube comments
AFP-Medialab/verification-plugin pull request #659
Opened 2024-11-18 16:19 UTC by twinkarma

Renders scraped youtube comments collected in the backend (see https://github.com/GateNLP/we-verify-app-assistant/issues/74).

2025-02-12 09:21 UTC, jmafoster1 commented
I just tried to run this on [this video](https://www.youtube.com/watch?v=grdu6UBK76w) and got the following error from the backend (from the `youtube-comments` branch)
```Traceback (most recent call last):
  File "/home/michael/Documents/GATE/backend/app/main/services/scrape_service.py", line 846, in scrape_youtube_comments
    video_title = json_response["items"][0]["snippet"]["title"]
                  ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
```
Have I done something wrong?

2025-02-12 09:22 UTC, jmafoster1 commented
I also noticed a few duplicated imports, which might indicate a problem with my pre-commit action. I'll look into that too

2025-02-12 09:25 UTC, rosannamilner commented
> I just tried to run this on [this video](https://www.youtube.com/watch?v=grdu6UBK76w) and got the following error from the backend (from the `youtube-comments` branch)
> 
> ```
>   File "/home/michael/Documents/GATE/backend/app/main/services/scrape_service.py", line 846, in scrape_youtube_comments
>     video_title = json_response["items"][0]["snippet"]["title"]
>                   ~~~~~~~~~~~~~^^^^^^^^^
> KeyError: 'items'
> ```
> 
> Have I done something wrong?

Yes I just had that too - I've just been trying to sort pylint/black so perhaps I've changed something. I'm about to go into a meeting but I'll have a look again later and let you know when it's ready.

2025-02-12 10:37 UTC, jmafoster1 commented
Thanks. It looks like it's an API thing. I printed `json_response` from the backend and it looks like this:
```
{'error': {'code': 403, 'message': "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.", 'errors': [{'message': "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.", 'domain': 'global', 'reason': 'forbidden'}], 'status': 'PERMISSION_DENIED'}}
```

2025-02-12 10:57 UTC, rosannamilner commented
> Thanks. It looks like it's an API thing. I printed `json_response` from the backend and it looks like this:
> 
> ```
> {'error': {'code': 403, 'message': "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.", 'errors': [{'message': "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.", 'domain': 'global', 'reason': 'forbidden'}], 'status': 'PERMISSION_DENIED'}}
> ```

Ah of course yes apologies, you'll need an API key for the youtube comments in .env which you can get following instructions on this page: https://www.getphyllo.com/post/how-to-get-youtube-api-key

```
YOUTUBE_API_KEY=
```

2025-02-12 11:25 UTC, jmafoster1 commented
Thanks, I'm now getting the comments coming though, but am getting "service failed" instead of the stance classifications:
![image](https://github.com/user-attachments/assets/31408765-3cd4-4c43-98a1-c960fb1fe53e)
In my console, it says "Could not connect to multilingual stance service". Any ideas?

2025-02-12 13:33 UTC, rosannamilner commented
> Thanks, I'm now getting the comments coming though, but am getting "service failed" instead of the stance classifications: ![image](https://private-user-images.githubusercontent.com/13611658/412398119-31408765-3cd4-4c43-98a1-c960fb1fe53e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkzNjczOTAsIm5iZiI6MTczOTM2NzA5MCwicGF0aCI6Ii8xMzYxMTY1OC80MTIzOTgxMTktMzE0MDg3NjUtM2NkNC00YzQzLTk4YTEtYzk2MGZiMWZlNTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjEyVDEzMzEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NzZkNmY2ZWFlYjJjZDgwYzc3MjJkZWI2ZDY4Yjc1OWRiYWZhYzk3MjJhM2ZiM2RjODA1NWI0NTA2ZmYwZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ubP06je6C7PUb4SYRNxUOi8DJBg4HY-TN3w2n-IbL9Y) In my console, it says "Could not connect to multilingual stance service". Any ideas?

So the error seems to be from the GATE side so hopefully that can be looked into soon. I have currently set it to scrape 10 comments (and their replies) which works for me.

2025-02-12 13:53 UTC, jmafoster1 commented
Thanks Rosanna, this looks to work for me too now, although the stance classifier is classifying the comment "+" as Deny. I guess that will need a specific issue on the stance classifier rather than here (if we believe it's worth looking into) as it doesn't affect the validity of this PR or the frontend one.

2025-02-12 13:54 UTC, jmafoster1 approved these changes

2025-02-19 11:38 UTC, rosannamilner commented
@Sallaa this is ready for review now. The multilingual stance classifier is currently set to collect 10 most relevant top level comments and their replies, and we're looking on the GATE side to get this working for more.

Corresponding translations PR: https://github.com/AFP-Medialab/InVID-Translations/pull/113

2025-02-19 12:28 UTC, Sallaa commented
@rosannamilner thank you. See my pending comment for the [caaVerificationKeywords.jsx](https://github.com/AFP-Medialab/verification-plugin/pull/659/files/4777f074f6c2edf6550c750ad6435696f864c1a0#diff-48b1e8ccc05b4cf8c47bf979a66c66a546289ed4cc4cf381aa1ccd17ce440b3d) up in the conversation

2025-02-24 14:30 UTC, Sallaa commented
> > @rosannamilner thank you. See my pending comment for the [caaVerificationKeywords.jsx](https://github.com/AFP-Medialab/verification-plugin/pull/659/files/4777f074f6c2edf6550c750ad6435696f864c1a0#diff-48b1e8ccc05b4cf8c47bf979a66c66a546289ed4cc4cf381aa1ccd17ce440b3d) up in the conversation
> 
> 
> 
> Apologies @Sallaa , I can't see the comment? Can you link it please?

https://github.com/AFP-Medialab/verification-plugin/pull/659#discussion_r1959519267

2025-02-25 08:49 UTC, rosannamilner commented
> [#659 (comment)](https://github.com/AFP-Medialab/verification-plugin/pull/659#discussion_r1959519267)

Thanks @Sallaa, although the link doesn't work for me it just directs me to this PR strangely! I see a brief preview about moving [caaVerificationKeywords.jsx](https://github.com/AFP-Medialab/verification-plugin/pull/659/files/4777f074f6c2edf6550c750ad6435696f864c1a0#diff-48b1e8ccc05b4cf8c47bf979a66c66a546289ed4cc4cf381aa1ccd17ce440b3d) to a .tsv file. I will look into this

2025-02-25 09:24 UTC, ianroberts commented
> See my pending comment

If you’re seeing a comment with the “pending” label that means that you’ve started a review but not yet finished it - when you add several comments as part of one review they show _to you_ as pending but don’t become visible to anyone else until you have finished the review and selected the comment/aporive/request changes option.

2025-02-26 09:10 UTC, Sallaa requested changes

2025-02-26 09:10 UTC, Sallaa commented on src/components/NavItems/Assistant/AssistantScrapeResults/caaVerificationKeywords.jsx
Should these be in a .tsv file instead? It'd be best to support all the languages that we currently support too (including Japanese).

2025-02-26 09:11 UTC, Sallaa commented
> > See my pending comment
> 
> If you’re seeing a comment with the “pending” label that means that you’ve started a review but not yet finished it - when you add several comments as part of one review they show _to you_ as pending but don’t become visible to anyone else until you have finished the review and selected the comment/approve/request changes option.

My bad, thank you @ianroberts -- it should be better now

2025-03-03 11:07 UTC, rosannamilner commented
Hi @Sallaa I've updated the array in caaVerificationKeywords.jsx to include the missing languages. However, I'm struggling to work out how to read in correctly from a TSV, tried a lot of options but no luck so far. Do you know how to do this and can you point me in the right direction please?

2025-03-18 16:08 UTC, merged